name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  build_ieee:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dockerfile: [
          "ieee"
        ]
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.${{ matrix.dockerfile }} --tag ${{ matrix.dockerfile }}:$(date +%s)  

  build_fuzzy:
    needs: build_ieee
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dockerfile: [
          "fuzzy",
          "fuzzy-numpy",
          "fuzzy-numpy-scipy",
          "fuzzy-numpy-scipy-sklearn"
        ]
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.${{ matrix.dockerfile }} --tag ${{ matrix.dockerfile }}:$(date +%s)